version: "3.3"

networks:
  dns_net:
    driver: overlay

volumes:
  etc-pihole:
  etc-dnsmasq.d:
  
services:
  pihole:
    image: pihole/pihole:v5.0
    networks:
      - dns_net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.hostname == raspberrypi2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: defaultwebpassword
#      DNS1: 172.18.0.2#5353
#      DNS2: 172.18.0.4#5353
    volumes:
      - etc-pihole:/etc/pihole
      - etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1

  unbound:
    image: klutchell/unbound:latest
    networks:
      - dns_net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
          - node.hostname == raspberrypi2
#    expose:
#      - "5353"